Makefile

to have a simple repeatable container build

add Docker build script

---

Makefile
docker-compose.yml

to show the workflow we'd like ported to Podman eventually

add Docker development stuffs

---

Makefile
containers/Dockerfile
containers/nginx-entrypoint
docker-compose.yml
package-lock.json
package.json
src/components/landingPage/LandingPage.tsx
src/index.html
src/services/config.ts
webpack.config.js

wanted to test that window propagates config alright and was struggling with mocking/unmocking the window, but then I don't see much value in such a test

add runtime configuration support via environment variables

---

src/store/ducks/user/actions.ts
src/store/ducks/user/mocks.ts
src/store/ducks/user/sagas.test.ts
src/store/ducks/user/sagas.ts

@renanrodrigo I squashed one commit short in the last PR. Created a new branch to incorporate these :broom:

fix: remove unnecessary eslint exceptions

---

README.md

When any user is creating an issue for the first time, they will be pointed to the contributing guide. For visibility, it should also appear in the README file.

chore: add contributing link to readme

---

src/components/mainScreen/MainScreen.tsx
src/store/ducks/lab/policy/actions.ts
src/store/ducks/lab/policy/index.ts
src/store/ducks/lab/policy/sagas.ts
src/store/ducks/lab/policy/types.ts
src/store/ducks/rootReducer.ts
src/store/ducks/rootSaga.ts
src/store/ducks/user/actions.ts
src/store/ducks/user/index.ts
src/store/ducks/user/reducer.test.ts
src/store/ducks/user/sagas.ts
src/store/ducks/user/types.ts
src/store/index.ts

Added 2 features: auto refresh token and connect API endpoints to Redux stores

Policy api and automatically refresh token

---

src/store/ducks/lab/policy/actions.ts
src/store/ducks/lab/policy/index.ts
src/store/ducks/lab/policy/sagas.ts
src/store/ducks/lab/policy/types.ts

Adding error handling messages for better displays of server side errors.

feat: add errMsg object to policy

---

src/store/ducks/lab/policy/sagas.ts

fix: remove logging for testing

---

src/components/mainScreen/MainScreen.tsx
src/components/mainScreen/PageWrapper.tsx
src/components/policies/Policies.tsx

Added the policy UI functionality

Added policy dashboard

---

src/components/policies/Policies.tsx
src/store/ducks/lab/policy/index.ts
src/store/ducks/lab/policy/sagas.ts
src/store/ducks/lab/policy/types.ts

Policy spec changes & bug fixes

---

package-lock.json
package.json

feat: add react-charts

---

package-lock.json
src/store/ducks/lab/policy/sagas.ts

The way that the API handles data returns has changed, breaking what the way we processed data. This PR fixes that

refactor: reflect API code

---

src/store/ducks/lab/product/actions.ts
src/store/ducks/lab/product/index.ts
src/store/ducks/lab/product/sagas.ts
src/store/ducks/lab/product/types.ts
src/store/ducks/lab/region/types.ts
src/store/ducks/rootReducer.ts
src/store/ducks/rootSaga.ts

Adding product API to comply with rhub-api

feat: add Products API

---

src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/steps/AdvancedConfiguration.tsx

This change depends on unmerged changes in #44.

Create Cluster Wizard: Step 4 Advanced Configuration

---

src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/helpers.tsx
src/components/QuickClusterWizard/steps/ClusterConfiguration.tsx
src/components/QuickClusterWizard/steps/Products.tsx
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/components/QuickClusterWizard/steps/Regions.tsx

Current Behavior: When a user hits 'Back', previous selections and input are 'forgotten'
Desired Behavior: Cache the answers and keep the inputs intact for users to go back and forth

Input cache

---

src/components/QuickClusterWizard/QuickClusterWizard.css
src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/helpers.tsx
src/components/QuickClusterWizard/steps/AdvancedConfiguration.tsx
src/components/QuickClusterWizard/steps/ClusterConfiguration.tsx
src/components/QuickClusterWizard/steps/Graphs.tsx
src/components/QuickClusterWizard/steps/Products.tsx
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/components/QuickClusterWizard/steps/Regions.tsx
src/components/QuickClusterWizard/steps/ResourceSummaryTable.tsx
src/components/QuickClusterWizard/steps/Review.tsx

1. Add comments to Props
2. Add Reservation Days 
3. Use Context API to fetch values of top-level component
4. Add a header for each step

Wizard improvements

---

src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/helpers.tsx
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/components/QuickClusterWizard/steps/Review.tsx
src/store/ducks/lab/cluster/sagas.ts
src/store/ducks/lab/cluster/types.ts

When the user hits Finish, we will create a newCluster object and submit to the API for a QuickCluster Creation job

implement logics when user hits Finish in QuickCluster Create Wizard 

---

__mocks__/labCluster.ts
__tests__/store/ducks/lab/cluster/reducer.test.ts
__tests__/store/ducks/lab/cluster/sagas.test.ts
src/components/clusterDetails/ClusterDetails.tsx
src/components/clusters/ClusterView.tsx
src/store/ducks/lab/cluster/actions.ts
src/store/ducks/lab/cluster/index.ts
src/store/ducks/lab/cluster/types.ts

Wrote tests for tests labCluster reducers and sagas

Lab cluster tests

---

package-lock.json
package.json

Some of our packages are dated, and we need to keep them up to date in order to comply with good security practices

Update dependency in webpack-dev-server

---

src/components/QuickClusterWizard/helpers.tsx
src/components/QuickClusterWizard/steps/ClusterConfiguration.tsx
src/components/QuickClusterWizard/steps/Questionnaire.tsx

When the user edits one kind of node, we update charts using selections on all nodes (related to EXD-RHUB646)

fix: fix chart update errors in cluster with multiple node types

---

__mocks__/labRegion.ts
__tests__/store/ducks/lab/region/reducer.test.ts
__tests__/store/ducks/lab/region/sagas.test.ts

#61 has linting problems, and this PR will resolve that

fix: lint tests for `ducks/lab/region`

---

.github/workflows/validate.yml

Enable linting for git workflow, so any linting issue (other than warnings) would fail the job

Add lint to workflow

---

__mocks__/labProduct.ts
__tests__/store/ducks/lab/product/reducer.test.ts
__tests__/store/ducks/lab/product/sagas.test.ts
src/store/ducks/lab/product/actions.ts
src/store/ducks/lab/product/types.ts

Introducing unit tests to `ducks/lab/products`, with a few improvements on sagas and types

feat: improve and add tests for ducks/lab/products

---

__tests__/components/landingPage/LandingPage.test.tsx

Adding tests for the LandingPage component.

Adds tests for LandingPage component

---

.github/workflows/validate.yml
Dockerfile.dev
containers/Dockerfile

Use latest node versions for validate

feat: use node v16 for CI

---

__mocks__/clusterView.ts
__mocks__/clusters.ts
__mocks__/services.ts
__tests__/components/clusters/ClusterTableUtilization.test.tsx
__tests__/components/clusters/ClusterView.test.tsx
__tests__/components/clusters/MyCluster.test.tsx
__tests__/components/clusters/SharedClusters.test.tsx

Adding tests and mocks for the components in the `src/components/clusters` directory.

Adds tests for the `src/components/clusters`

---

src/components/clusterDetails/ClusterDetails.css
src/components/clusterDetails/ClusterDetails.tsx
src/components/clusterDetails/cards/ClusterInfo.tsx

We added new buttons to copy fqdn of ClusterHost to clipboard

feat: truncate fqdn and add copy to clipboard button

---

__mocks__/labProduct.ts
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/store/ducks/lab/product/index.ts

Fixes:
- cluster_id minLength value
- cluster_id tooltip text
Added:
- cluster_id field validation

fix cluster_id min-length, tooltip, and add field validation

---

__mocks__/QuickClusterWizard.ts
__mocks__/labRegion.ts
__tests__/components/QuickClusterWizard/QuickClusterWizard.test.tsx
__tests__/components/QuickClusterWizard/steps/AdvancedConfiguration.test.tsx
__tests__/components/QuickClusterWizard/steps/ClusterConfiguration.test.tsx
__tests__/components/QuickClusterWizard/steps/Graphs.test.tsx
__tests__/components/QuickClusterWizard/steps/Products.test.tsx
__tests__/components/QuickClusterWizard/steps/Questionnaire.test.tsx
__tests__/components/QuickClusterWizard/steps/Region.test.tsx
__tests__/components/QuickClusterWizard/steps/ResourceSummaryTable.test.tsx
__tests__/components/QuickClusterWizard/steps/Review.test.tsx
__tests__/testUtils.tsx
src/components/QuickClusterWizard/QuickClusterWizard.tsx

Adding tests for the `QuickClusterWizard` component and all the components in the `src/components/QuickClusterWizard/steps` directory.

Components quick cluster wizard tests

---

__mocks__/labPolicy.ts
__mocks__/policies.ts
__tests__/components/policies/Policies.test.tsx
__tests__/store/ducks/lab/policy/reducer.test.ts
__tests__/store/ducks/lab/policy/sagas.test.ts

Adding tests and mocks for the sagas and reducer in `/lab/policy` and the `Policies` component.

Adding tests for /lab/policy and /components/policies

---

__mocks__/labLocation.ts
__mocks__/labPolicy.ts
__mocks__/labRegion.ts
__tests__/store/ducks/lab/location/reducer.test.ts
__tests__/store/ducks/lab/location/sagas.test.ts
src/components/QuickClusterWizard/steps/Regions.tsx
src/store/ducks/lab/location/actions.ts
src/store/ducks/lab/location/index.ts
src/store/ducks/lab/location/sagas.ts
src/store/ducks/lab/location/types.ts
src/store/ducks/lab/policy/types.ts
src/store/ducks/lab/region/types.ts
src/store/ducks/rootSaga.ts

Add UI support for https://github.com/resource-hub-dev/rhub-api/pull/94

ducks for lab/location API

---

__mocks__/services.ts
__tests__/components/mainScreen/CustomRoutes.test.tsx
__tests__/components/mainScreen/MainScreen.test.tsx
__tests__/components/mainScreen/Navigation.test.tsx

Adds unit tests for components in `components/mainScreen` directory and updates `__mocks__/services.ts` to test different keycloak scenarios.

Add tests for components/mainScreen

---

__mocks__/labCluster.ts
__tests__/components/towerOutput/TowerOutput.test.tsx
src/components/TowerOutput/TowerOutput.css
src/components/TowerOutput/TowerOutput.tsx
src/components/clusterDetails/cards/ClusterEvents.tsx
src/components/mainScreen/MainScreen.tsx
src/store/ducks/lab/cluster/actions.ts
src/store/ducks/lab/cluster/sagas.ts

Add TowerStdOutput page to the ClusterInfo when selecting the TowerJobID from the cluster history

feat: add towerstdout

---

__tests__/components/clusterDetails/cards/ClusterInfo.test.tsx
src/components/clusterDetails/ClusterDetails.css
src/components/clusterDetails/cards/ClusterInfo.tsx

feat: convert reboot button from text to icon

---

src/components/ResourcesDashboard/ResourcesDashboard.css
src/components/ResourcesDashboard/ResourcesDashboard.tsx
src/components/mainScreen/MainScreen.tsx
src/components/mainScreen/Navigation.tsx
src/components/quickClusterUserActivity/QuickClusterUserActivity.tsx

I created a placeholder component and links for User Activity for QuickCluster, so that all changes for User Activity will not affect the master branch

feat: add placeholder for QuickCluster Activity

---

__mocks__/QuickClusterWizard.ts
src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/helpers.tsx
src/store/ducks/lab/product/types.ts

1. Remove generateErrMsg 
2. Display messages straight from API

refactor: add message into condition

---

__mocks__/QuickClusterWizard.ts
__tests__/components/QuickClusterWizard/steps/Questionnaire.test.tsx
src/components/QuickClusterWizard/helpers.tsx

Adding the 'param_in' condition to check for substring matches in parameters.

feat: add param_in condition

---

__mocks__/clusterDetails.ts
__mocks__/labCluster.ts
__mocks__/labRegion.ts
__tests__/components/QuickClusterWizard/steps/Graphs.test.tsx
__tests__/components/clusterDetails/cards/ClusterEvents.test.tsx
__tests__/components/quickClusterUserActivity/QuickClusterUserActivity.test.tsx
src/components/QuickClusterWizard/steps/Graphs.tsx
src/components/clusterDetails/cards/ClusterEvents.tsx
src/components/clusterDetails/cards/Utilization.tsx
src/components/clusters/ClusterTableUtilization.tsx
src/components/quickClusterUserActivity/QuickClusterUserActivity.css
src/components/quickClusterUserActivity/QuickClusterUserActivity.tsx
src/components/quickClusterUserActivity/RegionalUsageTable.tsx
src/services/common.ts
src/store/ducks/lab/cluster/index.ts
src/store/ducks/lab/cluster/types.ts
src/store/ducks/lab/region/actions.ts
src/store/ducks/lab/region/index.ts
src/store/ducks/lab/region/types.ts

1. Add regional activity table
2. Refactor some fields from cluster to show names instead of just ids (users, groups, etc)
3. Fix tests

Regional activity

---

__mocks__/QuickClusterWizard.ts
__mocks__/clusterDetails.ts
__mocks__/labCluster.ts
__mocks__/labRegion.ts
__tests__/components/QuickClusterWizard/steps/Graphs.test.tsx
__tests__/components/ResourcesDashboard/ResourcesDashboard.test.tsx
__tests__/components/clusterDetails/cards/ClusterEvents.test.tsx
__tests__/components/quickClusterUserActivity/QuickClusterUserActivity.test.tsx
__tests__/store/ducks/lab/region/reducer.test.ts
__tests__/store/ducks/lab/region/sagas.test.ts
src/components/QuickClusterWizard/steps/ClusterConfiguration.tsx
src/components/QuickClusterWizard/steps/Graphs.tsx
src/components/QuickClusterWizard/steps/Review.tsx
src/components/ResourcesDashboard/ResourcesDashboard.css
src/components/ResourcesDashboard/ResourcesDashboard.tsx
src/components/clusterDetails/cards/ClusterEvents.tsx
src/components/clusterDetails/cards/Utilization.tsx
src/components/clusters/ClusterTableUtilization.tsx
src/components/mainScreen/MainScreen.tsx
src/components/mainScreen/Navigation.tsx
src/components/quickClusterUserActivity/QuickClusterUserActivity.css
src/components/quickClusterUserActivity/QuickClusterUserActivity.tsx
src/components/quickClusterUserActivity/RegionalUsageTable.tsx
src/services/common.ts
src/store/ducks/lab/cluster/index.ts
src/store/ducks/lab/cluster/types.ts
src/store/ducks/lab/region/actions.ts
src/store/ducks/lab/region/index.ts
src/store/ducks/lab/region/sagas.ts
src/store/ducks/lab/region/types.ts

Merging quickcluster_activity to master branch

Quickcluster activity

---

__mocks__/openstack.ts
__tests__/store/ducks/openstack/cloud/reducer.test.ts
__tests__/store/ducks/openstack/cloud/sagas.test.ts
src/store/ducks/openstack/cloud/actions.ts
src/store/ducks/openstack/cloud/index.ts
src/store/ducks/openstack/cloud/sagas.ts
src/store/ducks/openstack/cloud/types.ts
src/store/ducks/rootReducer.ts
src/store/ducks/rootSaga.ts

Adding OpenStack Cloud ducks for `openstack/cloud` endpoints

Openstack Cloud ducks

---

__mocks__/labPolicy.ts
__mocks__/labRegion.ts
__mocks__/openstack.ts
__tests__/store/ducks/openstack/project/reducer.test.ts
__tests__/store/ducks/openstack/project/sagas.test.ts
src/store/ducks/lab/location/actions.ts
src/store/ducks/lab/location/types.ts
src/store/ducks/lab/region/actions.ts
src/store/ducks/lab/types.ts
src/store/ducks/openstack/cloud/actions.ts
src/store/ducks/openstack/cloud/types.ts
src/store/ducks/openstack/project/actions.ts
src/store/ducks/openstack/project/index.ts
src/store/ducks/openstack/project/sagas.ts
src/store/ducks/openstack/project/types.ts
src/store/ducks/rootReducer.ts
src/store/ducks/rootSaga.ts
src/store/ducks/types.ts

Add openstack project duck to support `/openstack/project`

Openstack project duck

---

src/store/ducks/rootReducer.ts
src/store/index.ts

add labLocation, openstackCloud, openstackProject to AppState and rootReducer

fix: add missing states to AppState and rootReducer

---

__mocks__/labPolicy.ts
__mocks__/policies.ts
__tests__/components/QuickClusterWizard/QuickClusterWizard.test.tsx
__tests__/components/policies/Policies.test.tsx
__tests__/store/ducks/lab/policy/reducer.test.ts
__tests__/store/ducks/lab/policy/sagas.test.ts
src/components/policies/Policies.tsx
src/components/policies/PolicyForm.css
src/components/policies/PolicyForm.tsx
src/components/policies/formField/ControlledField.tsx
src/components/policies/formField/Cost.tsx
src/components/policies/formField/Density.tsx
src/components/policies/formField/Limit.tsx
src/components/policies/formField/Location.tsx
src/components/policies/formField/ScheduleAvailability.tsx
src/components/policies/formField/ServiceAvailability.tsx
src/components/policies/formField/Tag.tsx
src/components/policies/helpers.ts
src/store/ducks/lab/policy/actions.ts
src/store/ducks/lab/policy/sagas.ts
src/store/ducks/lab/policy/types.ts

Add a Setup Form for Creating and Editing Policies

---

__mocks__/dns.ts
__mocks__/satellite.ts
__tests__/store/ducks/dns/reducer.test.ts
__tests__/store/ducks/dns/sagas.test.ts
__tests__/store/ducks/satellite/reducer.test.ts
__tests__/store/ducks/satellite/sagas.test.ts
src/store/ducks/dns/actions.ts
src/store/ducks/dns/index.ts
src/store/ducks/dns/sagas.ts
src/store/ducks/dns/types.ts
src/store/ducks/rootReducer.ts
src/store/ducks/rootSaga.ts
src/store/ducks/satellite/actions.ts
src/store/ducks/satellite/index.ts
src/store/ducks/satellite/sagas.ts
src/store/ducks/satellite/types.ts
src/store/index.ts

[Connect Satellite API to UI](https://issues.redhat.com/browse/EXDRHUB-1078)
[Connect DNS API to UI](https://issues.redhat.com/browse/EXDRHUB-1079)

Satellite + DNS server redux modules

---

package-lock.json
package.json

feat: add socket client

---

src/components/toastNotifications/ToastNotifications.tsx

add messaging module to rhub-app for notification on cluster status change

Add messaging module to rhub-app for notification

---

.husky/pre-push
package-lock.json
package.json
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/components/clusterDetails/cards/Utilization.tsx
src/components/policies/PolicyForm.tsx
src/components/policies/formField/Cost.tsx
src/components/toastNotifications/ToastNotifications.tsx

Updated packages with high vulnerability dependencies:
- @patternfly/react-charts
- html-loader
- husky
Removed `@types/socket.io-client` due to deprecation

feat: updated npm dependencies packages

---

src/components/policies/formField/ControlledField.tsx
src/components/policies/formField/Cost.tsx
src/components/policies/formField/Limit.tsx
src/components/policies/formField/Location.tsx
src/components/policies/formField/ScheduleAvailability.tsx
src/components/policies/formField/Tag.tsx
src/components/policies/helpers.ts

Added tooltips to the policy form.

Policy improvements

---

src/components/policies/helpers.ts
src/store/ducks/lab/policy/index.ts

fix: Location field always enabled on Edit Policy

---

__tests__/store/ducks/lab/location/reducer.test.ts
__tests__/store/ducks/lab/policy/reducer.test.ts
__tests__/store/ducks/lab/policy/sagas.test.ts
src/components/pageError/pageError.tsx
src/components/policies/Policies.tsx
src/components/policies/helpers.ts
src/services/common.ts
src/store/ducks/lab/location/actions.ts
src/store/ducks/lab/location/sagas.ts
src/store/ducks/lab/policy/actions.ts
src/store/ducks/lab/policy/index.ts
src/store/ducks/lab/policy/sagas.ts
src/store/ducks/lab/policy/types.ts

Added an error page when policy is failing to load

Add error page policy

---

__tests__/components/quickClusterUserActivity/QuickClusterUserActivity.test.tsx
__tests__/store/ducks/lab/region/reducer.test.ts
src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/quickClusterUserActivity/QuickClusterUserActivity.tsx
src/store/ducks/lab/region/actions.ts
src/store/ducks/lab/region/index.ts
src/store/ducks/lab/region/sagas.ts

Add error handling to QuickClusterActivity

Myactivityerror

---

__tests__/components/QuickClusterWizard/QuickClusterWizard.test.tsx
src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/steps/Questionnaire.tsx
src/components/QuickClusterWizard/steps/Regions.tsx

Adding error rendering for Wizard

feat: add error handling in wizard

---

__tests__/components/QuickClusterWizard/steps/Region.test.tsx
src/components/QuickClusterWizard/steps/Regions.tsx
src/components/pageError/pageError.tsx

When there are no region available for a certain product, we should display a message to denote that error.

No region wizard

---

package-lock.json
package.json
src/components/clusters/MyClusters.tsx
src/components/toastNotifications/ToastNotifications.tsx

Adding notifications to MyClusters

Stomp notifications

---

__tests__/components/loginPage/Login.test.tsx
package-lock.json
package.json
src/components/loginPage/Login.tsx
src/components/loginPage/login.css
src/index.html
src/services/config.ts
webpack.config.js

Adding a new log in page for RHUB, adding skeletal support for Red Hat SSO as well as LDAP (for admin users)

Login page

---

src/components/clusterDetails/ClusterDetails.tsx

hoisting AuthorizedFunction call up to prevent rendering error in ClusterDetails

fix: hoisting AuthorizedFunction call up to prevent rendering error 

---

docker-compose.yml
src/components/toastNotifications/ToastNotifications.tsx

fix: fetching bug for messaging and adding refresh 

---

src/components/landingPage/LandingPage.tsx

As titled, this PR removes some links that were not removed in the last PR, as well as adding <div> for CustomLink component for better display

Remove more empty links and add <div> to links

---

src/components/toastNotifications/ToastNotifications.tsx

Secure `wss` is needed on prod

feat: add wss to protocol

---

__mocks__/clusters.ts
__mocks__/user.ts
__tests__/components/clusters/MyCluster.test.tsx
src/components/clusterDetails/cards/ClusterInfo.tsx
src/components/clusters/MyClusters.tsx
src/components/clusters/SharedClusters.tsx
src/components/generalNotifications/GeneralNotifications.tsx

Added a general notifications component and added a warning to alert the user when they have not added any SSH public keys to their profile.

feat: add general notification for missing SSH keys

---

__mocks__/QuickClusterWizard.ts
src/components/QuickClusterWizard/QuickClusterWizard.css
src/components/QuickClusterWizard/QuickClusterWizard.tsx
src/components/QuickClusterWizard/steps/AdvancedConfiguration.tsx
src/components/QuickClusterWizard/steps/ClusterConfiguration.tsx
src/components/QuickClusterWizard/steps/Products.tsx
src/components/QuickClusterWizard/steps/Regions.tsx

Duplicate of #155. My fork was deleted somehow so #155 was not able to merge.

Enable select card

---

__mocks__/clusterDetails.ts
__tests__/components/clusterDetails/ClusterDetails.test.tsx
__tests__/components/clusterDetails/cards/ClusterLifespan.test.tsx
src/components/clusterDetails/ClusterDetails.tsx
src/components/clusterDetails/cards/ClusterLifespan.tsx

- Display N/A for Shared Cluster expiration
- Remove delete button on Shared Cluster

Shared Cluster fixes

---

webpack.dev.js
webpack.prod.js

Adding two variables to Webpack files

feat: add Broker var into webpack

---

containers/nginx-entrypoint
src/App.tsx
src/components/toastNotifications/ToastNotifications.tsx
src/index.html
src/services/config.ts

chore: add nginx variables
